[workspace]
members = [
    "crates/common",
    "crates/compiler",
    "crates/crypto",
    "crates/ethereum",
    "crates/executor",
    "crates/gateway-client",
    "crates/gateway-test-fixtures",
    "crates/gateway-types",
    "crates/merkle-tree",
    "crates/p2p",
    "crates/p2p_proto",
    "crates/p2p_proto_derive",
    "crates/p2p_stream",
    "crates/pathfinder",
    "crates/retry",
    "crates/rpc",
    "crates/serde",
    "crates/storage",
]
exclude = [
    "crates/load-test",
    "crates/stark_hash_python",
    "utils/pathfinder-probe",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true

[profile.dev.package.flate2]
opt-level = 3

[workspace.package]
version = "0.11.3"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.76"
authors = ["Equilibrium Labs <info@equilibrium.co>"]

[workspace.dependencies]
anyhow = "1.0.75"
assert_matches = "1.5.0"
async-trait = "0.1.73"
axum = "0.6.19"
base64 = "0.13.1"
bitvec = "1.0.1"
blockifier = "=0.5.0"
bytes = "1.4.0"
cached = "0.44.0"
# This one needs to match the version used by blockifier
cairo-vm = "=0.9.2"
clap = "4.1.13"
const_format = "0.2.31"
criterion = "0.5.1"
fake = "2.8.0"
flate2 = "1.0.27"
futures = { version = "0.3", default-features = false }
hex = "0.4.3"
http = "0.2.9"
httpmock = "0.7.0-rc.1"
ipnet = "2.9.0"
lazy_static = "1.4.0"
metrics = "0.20.1"
num-bigint = "0.4.4"
primitive-types = "0.12.1"
pretty_assertions_sorted = "1.2.3"
rand = "0.8.5"
rayon = "1.8.0"
reqwest = "0.11.18"
rstest = "0.18.2"
semver = "1.0.18"
serde = "1.0.192"
serde_json = "1.0.105"
serde_with = "3.0.0"
sha3 = "0.10"
smallvec = "1.13.1"
# This one needs to match the version used by blockifier
starknet_api = "=0.10.0"
test-log = { version = "0.2.12", default-features = false }
thiserror = "1.0.48"
tokio = "1.32.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
zstd = "0.12.4"
ark-ff = "0.4.2"
async-stream = "0.3.5"
bincode = "2.0.0-rc.3"
bloomfilter = "1.0.12"
cairo-lang-starknet-classes = "=2.6.0"
casm-compiler-v1_0_0-alpha6 = { git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-alpha.6" }
casm-compiler-v1_0_0-rc0 = { git = "https://github.com/starkware-libs/cairo", tag = "v1.0.0-rc0" }
casm-compiler-v1_1_1 = "=1.1.1"
casm-compiler-v2 = "=2.6.0"
console-subscriber = "0.1.10"
const-decoder = "0.3.0"
data-encoding = "2.4.0"
env_logger = "0.10.0"
ff = "0.13"
futures-bounded = "0.2.1"
hyper = "0.14.27"
jemallocator = "0.5.4"
keccak-hash = "0.10.0"
libp2p = { version = "0.53.0", default-features = false }
libp2p-identity = "0.2.2"
libp2p-plaintext = "0.41.0"
libp2p-swarm-test = "0.3.0"
metrics-exporter-prometheus = "0.11.0"
mime = "0.3"
mockall = "0.11.4"
paste = "1.0.14"
proc-macro2 = "1.0.66"
proptest = "1.2.0"
prost = "0.12.1"
prost-build = "0.12.1"
prost-types = "0.12.1"
quote = "1.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rand_chacha = "0.3.1"
rusqlite = "0.28.0"
sha2 = "0.10.7"
syn = "1.0"
tempfile = "3.8"
time = "0.3.28"
tokio-retry = "0.3.0"
tokio-stream = "0.1.14"
tokio-tungstenite = "0.20"
tower = { version = "0.4.13", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
unsigned-varint = "0.8.0"
url = "2.4.1"
vergen = { version = "8", default-features = false }
void = "1.0.2"
warp = "0.3.5"
zeroize = "1.6.0"
