[package]
name = "pathfinder-probe"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

[dependencies]
anyhow = "1.0.81"
axum = { version = "0.6.20", features = ["macros"] }
futures = "0.3.30"
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.2"
reqwest = { version = "0.11.27", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
