[package]
name = "pathfinder-retry"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
tokio-retry = "0.3.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "test-util"] }
