[package]
name = "p2p_proto_derive"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0"
syn = "1.0"
